"""Added created_at to Contact

Revision ID: 1b0d2c7bc522
Revises: 5d203fccd714
Create Date: 2025-07-06 02:32:44.390245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0d2c7bc522'
down_revision = '5d203fccd714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
