"""Add verification_token and role field 

Revision ID: 2cfd77b0374a
Revises: c5bba6f9ff0c
Create Date: 2025-07-05 23:25:21.060741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfd77b0374a'
down_revision = 'c5bba6f9ff0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint('uq_user_verification_token', ['verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_verification_token', ['verification_token'])
        batch_op.drop_column('role')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
