"""Add email field to User

Revision ID: 476c104c6574
Revises: 
Create Date: 2025-07-05 22:16:22.864717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476c104c6574'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False, server_default='example@example.com'))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.drop_column('username')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
