"""Add user_id to Contact

Revision ID: 5d203fccd714
Revises: c74f0ce45c04
Create Date: 2025-07-06 01:32:03.964737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d203fccd714'
down_revision = 'c74f0ce45c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_contact_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_contact_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
