"""update constraint

Revision ID: 895e743931b2
Revises: 2cfd77b0374a
Create Date: 2025-07-05 23:34:48.660133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895e743931b2'
down_revision = '2cfd77b0374a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['name'])

    # ### end Alembic commands ###
